// Arkaworld Product Database
const productsDatabase = {
  "bike-48v-20ah": {
    name: "48V 20Ah Lithium",
    category: "bike",
    badge: "Lithium",
    brand: "OKAYA EV",
    image: "battery-bike.jpeg",
    specs: "48V • 20Ah • 960Wh • LFP • 1000+ Cycles • 8.5 kg",
    price: "Wholesale / On Enquiry",
    description: "Drop-in replacement for lead-acid bike batteries. 60% lighter, 80+ km range on single charge. 3-4 hour fast charge. Zero maintenance. Smart BMS. 3+ year lifespan. Universal fit most electric bikes.",
    details: {
      voltage: "48V",
      capacity: "20Ah",
      energy: "960Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "1000+",
      weight: "8.5 kg",
      range: "80-100 km per charge",
      chargeTime: "3-4 hours",
      warranty: "3 years",
      maintenance: "Zero maintenance",
      ipRating: "IP54"
    },
    relatedCategory: "bike"
  },
  "bike-60v-25ah": {
    name: "60V 25Ah Premium",
    category: "bike",
    badge: "Premium",
    brand: "TRONTEK",
    image: "battery-bike.jpeg",
    specs: "60V • 25Ah • 1500Wh • LFP • 1200+ Cycles • 10.5 kg",
    price: "Wholesale / On Enquiry",
    description: "High-voltage premium e-bike battery. 100-120 km extended range. Superior hill-climbing power. 2-3 hour quick charge. Integrated thermal management. Bluetooth battery monitoring. 4+ year lifespan.",
    details: {
      voltage: "60V",
      capacity: "25Ah",
      energy: "1500Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "1200+",
      weight: "10.5 kg",
      range: "100-120 km per charge",
      chargeTime: "2-3 hours",
      warranty: "4 years",
      maintenance: "Zero maintenance",
      ipRating: "IP65"
    },
    relatedCategory: "bike"
  },
  "bike-72v-30ah": {
    name: "72V 30Ah Ultra",
    category: "bike",
    badge: "Ultra",
    brand: "EXIDE LIVO",
    image: "battery-bike.jpeg",
    specs: "72V • 30Ah • 2160Wh • NMC • 1000+ Cycles • 12 kg",
    price: "Wholesale / On Enquiry",
    description: "Ultra-high performance e-bike system. 150+ km extreme range. Dual-motor compatible. 2C continuous discharge. Fast 2-hour charge. Military-grade BMS. Stacking capable. 5-year warranty available.",
    details: {
      voltage: "72V",
      capacity: "30Ah",
      energy: "2160Wh",
      chemistry: "NMC",
      cycles: "1000+",
      weight: "12 kg",
      range: "150+ km per charge",
      chargeTime: "2 hours",
      warranty: "5 years",
      maintenance: "Smart BMS monitoring",
      ipRating: "IP67"
    },
    relatedCategory: "bike"
  },
  "scooter-48v-15ah": {
    name: "48V 15Ah Entry",
    category: "scooter",
    badge: "Entry",
    brand: "OKAYA",
    image: "battery-ev.jpeg",
    specs: "48V • 15Ah • 720Wh • LFP • 1000+ Cycles • 6 kg",
    price: "Wholesale / On Enquiry",
    description: "Perfect entry-level e-scooter battery. Lightweight at just 6 kg. 40-50 km range per charge. 3-4 hour charge time. Standard connector fit. IP54 weatherproof. Smart BMS. 2-3 year lifespan.",
    details: {
      voltage: "48V",
      capacity: "15Ah",
      energy: "720Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "1000+",
      weight: "6 kg",
      range: "40-50 km per charge",
      chargeTime: "3-4 hours",
      warranty: "2-3 years",
      maintenance: "Zero maintenance",
      ipRating: "IP54"
    },
    relatedCategory: "scooter"
  },
  "scooter-60v-20ah": {
    name: "60V 20Ah Standard",
    category: "scooter",
    badge: "Standard",
    brand: "OEM",
    image: "battery-ev.jpeg",
    specs: "60V • 20Ah • 1200Wh • LFP • 1200+ Cycles • 8.5 kg",
    price: "Wholesale / On Enquiry",
    description: "Standard 60V e-scooter battery. 60-80 km guaranteed range. 4-5 hour charge. Dual battery stackable. Standard 60V connectors. Smart BMS with Bluetooth. 3+ year lifespan.",
    details: {
      voltage: "60V",
      capacity: "20Ah",
      energy: "1200Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "1200+",
      weight: "8.5 kg",
      range: "60-80 km per charge",
      chargeTime: "4-5 hours",
      warranty: "3+ years",
      maintenance: "Smart BMS monitoring",
      ipRating: "IP65"
    },
    relatedCategory: "scooter"
  },
  "scooter-72v-30ah": {
    name: "72V 30Ah Performance",
    category: "scooter",
    badge: "Performance",
    brand: "TRONTEK",
    image: "battery-ev.jpeg",
    specs: "72V • 30Ah • 2160Wh • NMC • 1000+ Cycles • 11 kg",
    price: "Wholesale / On Enquiry",
    description: "High-performance 72V scooter battery. 100-130 km extreme range. 3C peak discharge for powerful acceleration. 2-hour fast charge. CAN bus ready. Enterprise BMS. Warranty upgrade to 4 years.",
    details: {
      voltage: "72V",
      capacity: "30Ah",
      energy: "2160Wh",
      chemistry: "NMC",
      cycles: "1000+",
      weight: "11 kg",
      range: "100-130 km per charge",
      chargeTime: "2 hours",
      warranty: "4 years",
      maintenance: "Remote monitoring capable",
      ipRating: "IP67"
    },
    relatedCategory: "scooter"
  },
  "car-12v-100ah": {
    name: "12V 100Ah LiFePO4",
    category: "car",
    badge: "Drop-In",
    brand: "AMARON",
    image: "battery-car2.jpeg",
    specs: "12V • 100Ah • 1200Wh • LFP • 2000+ Cycles • 13 kg",
    price: "Wholesale / On Enquiry",
    description: "Direct lead-acid replacement for cars. 60% lighter, 50% longer lifespan. Universal fit battery tray. Smart BMS protection. 3-5 year warranty. Premium inverter-compatible.",
    details: {
      voltage: "12V",
      capacity: "100Ah",
      energy: "1200Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "2000+",
      weight: "13 kg",
      range: "3-5x longer lifespan vs lead-acid",
      chargeTime: "5-6 hours",
      warranty: "3-5 years",
      maintenance: "Zero maintenance",
      ipRating: "IP54"
    },
    relatedCategory: "car"
  },
  "car-24v-50ah": {
    name: "24V 50Ah LiFePO4",
    category: "car",
    badge: "Dual",
    brand: "EXIDE",
    image: "battery-car2.jpeg",
    specs: "24V • 50Ah • 1200Wh • LFP • 2000+ Cycles • 22 kg",
    price: "Wholesale / On Enquiry",
    description: "Dual-battery system alternative for heavy-duty vehicles. 1200Wh output. 1000+ cycle life. Lightweight composite case. Ideal for regenerative braking systems. Smart load balancing.",
    details: {
      voltage: "24V",
      capacity: "50Ah",
      energy: "1200Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "2000+",
      weight: "22 kg",
      range: "Extended vehicle range with dual setup",
      chargeTime: "6-7 hours",
      warranty: "3-5 years",
      maintenance: "Zero maintenance",
      ipRating: "IP54"
    },
    relatedCategory: "car"
  },
  "car-48v-30ah": {
    name: "48V 30Ah EV",
    category: "car",
    badge: "EV",
    brand: "OKAYA EV",
    image: "battery-car2.jpeg",
    specs: "48V • 30Ah • 1440Wh • LFP • 2000+ Cycles • 28 kg",
    price: "Wholesale / On Enquiry",
    description: "48V electric vehicle battery. 1440Wh nominal output. Perfect for electric golf carts & forklifts. Stacking for larger systems. Smart BMS with CAN support. 80% usable capacity. 5+ year lifespan.",
    details: {
      voltage: "48V",
      capacity: "30Ah",
      energy: "1440Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "2000+",
      weight: "28 kg",
      range: "150-180 km vehicle range",
      chargeTime: "5-6 hours",
      warranty: "5+ years",
      maintenance: "Smart BMS monitoring",
      ipRating: "IP65"
    },
    relatedCategory: "car"
  },
  "car-60v-40ah": {
    name: "60V 40Ah EV+",
    category: "car",
    badge: "EV+",
    brand: "LIVGUARD",
    image: "battery-car2.jpeg",
    specs: "60V • 40Ah • 2400Wh • LFP • 2000+ Cycles • 38 kg",
    price: "Wholesale / On Enquiry",
    description: "High-power 60V EV battery for premium electric vehicles. 2400Wh capacity. Extended 200+ km range. Dual-motor compatible. IP65 weatherproof. Smart app monitoring. Enterprise warranty available.",
    details: {
      voltage: "60V",
      capacity: "40Ah",
      energy: "2400Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "2000+",
      weight: "38 kg",
      range: "200+ km extended range",
      chargeTime: "4-5 hours",
      warranty: "5+ years",
      maintenance: "App-based monitoring",
      ipRating: "IP65"
    },
    relatedCategory: "car"
  },
  "cycle-24v-10ah": {
    name: "24V 10Ah LFP",
    category: "cycle",
    badge: "Entry",
    brand: "OEM",
    image: "battery-bike.jpeg",
    specs: "24V • 10Ah • 240Wh • LFP • 1000+ Cycles • 1.8 kg",
    price: "Wholesale / On Enquiry",
    description: "Lightweight entry e-cycle battery. Just 1.8 kg for easy portability. 25-35 km range on single charge. 2-3 hour charge time. IP54 weatherproof. Smart BMS. Perfect for commuters.",
    details: {
      voltage: "24V",
      capacity: "10Ah",
      energy: "240Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "1000+",
      weight: "1.8 kg",
      range: "25-35 km per charge",
      chargeTime: "2-3 hours",
      warranty: "2 years",
      maintenance: "Zero maintenance",
      ipRating: "IP54"
    },
    relatedCategory: "cycle"
  },
  "cycle-36v-15ah": {
    name: "36V 15Ah LFP",
    category: "cycle",
    badge: "Standard",
    brand: "OKAYA",
    image: "battery-bike.jpeg",
    specs: "36V • 15Ah • 540Wh • LFP • 1200+ Cycles • 2.4 kg",
    price: "Wholesale / On Enquiry",
    description: "Standard 36V e-cycle battery. 45-60 km per charge range. 2.4 kg weight. 2-3 hour quick charge. Modular connector. Smart BMS with Bluetooth. 3+ year lifespan.",
    details: {
      voltage: "36V",
      capacity: "15Ah",
      energy: "540Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "1200+",
      weight: "2.4 kg",
      range: "45-60 km per charge",
      chargeTime: "2-3 hours",
      warranty: "3 years",
      maintenance: "Smart BMS monitoring",
      ipRating: "IP54"
    },
    relatedCategory: "cycle"
  },
  "cycle-48v-20ah": {
    name: "48V 20Ah LFP",
    category: "cycle",
    badge: "Premium",
    brand: "TRONTEK",
    image: "battery-bike.jpeg",
    specs: "48V • 20Ah • 960Wh • LFP • 1500+ Cycles • 3.2 kg",
    price: "Wholesale / On Enquiry",
    description: "Premium 48V e-cycle battery. 70-100 km extended range. 3.2 kg lightweight. Fast 2-3 hour charge. Dual battery stackable. IP65 weatherproof. 4+ year lifespan.",
    details: {
      voltage: "48V",
      capacity: "20Ah",
      energy: "960Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "1500+",
      weight: "3.2 kg",
      range: "70-100 km per charge",
      chargeTime: "2-3 hours",
      warranty: "4 years",
      maintenance: "Smart BMS with app",
      ipRating: "IP65"
    },
    relatedCategory: "cycle"
  },
  "rickshaw-12v-100ah": {
    name: "12V 100Ah",
    category: "rickshaw",
    badge: "Entry",
    brand: "SF SONIC",
    image: "battery-ev.jpeg",
    specs: "12V • 100Ah • 1200Wh • Lead-Acid • 500+ Cycles",
    price: "Wholesale / On Enquiry",
    description: "Standard entry 12V lead-acid for auto-rickshaws. Reliable 40-50 km range per charge. 4-5 hour charge. Universal fit auto-rickshaw tray. Heavy (45 kg) but proven reliable.",
    details: {
      voltage: "12V",
      capacity: "100Ah",
      energy: "1200Wh",
      chemistry: "Lead-Acid",
      cycles: "500+",
      weight: "45 kg",
      range: "40-50 km per charge",
      chargeTime: "4-5 hours",
      warranty: "1 year",
      maintenance: "Frequent watering required",
      ipRating: "IP45"
    },
    relatedCategory: "rickshaw"
  },
  "rickshaw-12v-150ah": {
    name: "12V 150Ah Cargo",
    category: "rickshaw",
    badge: "Cargo",
    brand: "AMARON",
    image: "battery-ev.jpeg",
    specs: "12V • 150Ah • 1800Wh • Lead-Acid • 600+ Cycles",
    price: "Wholesale / On Enquiry",
    description: "Cargo variant with extended range. 60-70 km per load. Heavy-duty for goods transport. 5-6 hour charge time. 60+ kg weight. Robust terminals.",
    details: {
      voltage: "12V",
      capacity: "150Ah",
      energy: "1800Wh",
      chemistry: "Lead-Acid",
      cycles: "600+",
      weight: "60 kg",
      range: "60-70 km per charge",
      chargeTime: "5-6 hours",
      warranty: "1-2 years",
      maintenance: "Frequent maintenance",
      ipRating: "IP45"
    },
    relatedCategory: "rickshaw"
  },
  "rickshaw-12v-200ah": {
    name: "12V 200Ah Heavy Duty",
    category: "rickshaw",
    badge: "HD",
    brand: "EXIDE",
    image: "battery-ev.jpeg",
    specs: "12V • 200Ah • 2400Wh • Lead-Acid • 700+ Cycles",
    price: "Wholesale / On Enquiry",
    description: "Heavy-duty 12V for commercial 24/7 operations. Extended 80-100 km range. Twin shift capable. 6-7 hour charge. 75+ kg massive capacity. Extreme reliability.",
    details: {
      voltage: "12V",
      capacity: "200Ah",
      energy: "2400Wh",
      chemistry: "Lead-Acid",
      cycles: "700+",
      weight: "75 kg",
      range: "80-100 km per charge",
      chargeTime: "6-7 hours",
      warranty: "1-2 years",
      maintenance: "Regular maintenance needed",
      ipRating: "IP45"
    },
    relatedCategory: "rickshaw"
  },
  "rickshaw-51v-100ah-lith": {
    name: "51.2V 100Ah LiFePO4",
    category: "rickshaw",
    badge: "Lithium",
    brand: "OKAYA EV",
    image: "battery-ev.jpeg",
    specs: "51.2V • 100Ah • 5.12kWh • 2000+ Cycles • 42 kg",
    price: "Wholesale / On Enquiry",
    description: "Direct upgrade from lead-acid. Drop-in compatible. 100-120 km range. 3-4 hour fast charge. 60% lighter. Smart BMS. Zero maintenance. 5+ year lifespan. 80% DoD usable.",
    details: {
      voltage: "51.2V",
      capacity: "100Ah",
      energy: "5.12kWh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "2000+",
      weight: "42 kg",
      range: "100-120 km per charge",
      chargeTime: "3-4 hours",
      warranty: "5+ years",
      maintenance: "Zero maintenance",
      ipRating: "IP65"
    },
    relatedCategory: "rickshaw"
  },
  "rickshaw-60v-100ah-lith": {
    name: "60.8V 100Ah LiFePO4",
    category: "rickshaw",
    badge: "High Power",
    brand: "TRONTEK",
    image: "battery-ev.jpeg",
    specs: "60.8V • 100Ah • 6.08kWh • 2000+ Cycles • 45 kg",
    price: "Wholesale / On Enquiry",
    description: "High-voltage system for powerful e-rickshaws. Extended 120-140 km range. 2-3 hour fast charge. Universal controller compatibility. Smart BMS with app monitoring. 5+ years daily use.",
    details: {
      voltage: "60.8V",
      capacity: "100Ah",
      energy: "6.08kWh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "2000+",
      weight: "45 kg",
      range: "120-140 km per charge",
      chargeTime: "2-3 hours",
      warranty: "5+ years",
      maintenance: "Smart BMS monitoring",
      ipRating: "IP65"
    },
    relatedCategory: "rickshaw"
  },
  "rickshaw-73v-100ah-lith": {
    name: "73.6V 100Ah LiFePO4",
    category: "rickshaw",
    badge: "Premium",
    brand: "OKAYA EV",
    image: "battery-ev.jpeg",
    specs: "73.6V • 100Ah • 7.36kWh • 2000+ Cycles • 48 kg",
    price: "Wholesale / On Enquiry",
    description: "Premium long-range. 140-160 km extended range on single charge. 2-3 hour charge time. IP65 weatherproof. Remote monitoring capable. Twin battery system scalable. 5+ year lifespan.",
    details: {
      voltage: "73.6V",
      capacity: "100Ah",
      energy: "7.36kWh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "2000+",
      weight: "48 kg",
      range: "140-160 km per charge",
      chargeTime: "2-3 hours",
      warranty: "5+ years",
      maintenance: "Remote monitoring capable",
      ipRating: "IP65"
    },
    relatedCategory: "rickshaw"
  },
  "rickshaw-51v-200ah-lith": {
    name: "51.2V 200Ah LiFePO4",
    category: "rickshaw",
    badge: "HC",
    brand: "EXIDE LIVO",
    image: "battery-ev.jpeg",
    specs: "51.2V • 200Ah • 10.24kWh • 2000+ Cycles • 82 kg",
    price: "Wholesale / On Enquiry",
    description: "High-capacity fleet solution. 150+ km guaranteed range. Multi-shift operations (24-hour turnover). Scalable dual-battery setup. Smart BMS. Heavy-duty for commercial fleets. 5+ year warranty available.",
    details: {
      voltage: "51.2V",
      capacity: "200Ah",
      energy: "10.24kWh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "2000+",
      weight: "82 kg",
      range: "150+ km per charge",
      chargeTime: "3-4 hours",
      warranty: "5+ years",
      maintenance: "Smart BMS management",
      ipRating: "IP65"
    },
    relatedCategory: "rickshaw"
  },
  "rickshaw-60v-200ah-lith": {
    name: "60.8V 200Ah LiFePO4",
    category: "rickshaw",
    badge: "UHC",
    brand: "TRONTEK",
    image: "battery-ev.jpeg",
    specs: "60.8V • 200Ah • 12.16kWh • 2000+ Cycles • 90 kg",
    price: "Wholesale / On Enquiry",
    description: "Ultra-high capacity for peak demand. 160-180 km assured range. 24/7 fleet operations. Multiple charging stations setup. Remote fleet monitoring available. Enterprise-grade BMS.",
    details: {
      voltage: "60.8V",
      capacity: "200Ah",
      energy: "12.16kWh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "2000+",
      weight: "90 kg",
      range: "160-180 km per charge",
      chargeTime: "3-4 hours",
      warranty: "5+ years",
      maintenance: "Enterprise BMS",
      ipRating: "IP65"
    },
    relatedCategory: "rickshaw"
  },
  "ev-48v-27ah": {
    name: "48V 27Ah LFP",
    category: "ev",
    badge: "Trail",
    brand: "OEM",
    image: "battery-ev.jpeg",
    specs: "48V • 27Ah • 1296Wh • LFP • 1500+ Cycles • 11.5 kg",
    price: "Wholesale / On Enquiry",
    description: "Perfect trail e-scooter. Guaranteed 60 km range. 3-4 hour charge. Standard 48V connector. IP65 weatherproof. Smart BMS. 3+ year lifespan.",
    details: {
      voltage: "48V",
      capacity: "27Ah",
      energy: "1296Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "1500+",
      weight: "11.5 kg",
      range: "60 km per charge",
      chargeTime: "3-4 hours",
      warranty: "3 years",
      maintenance: "Zero maintenance",
      ipRating: "IP65"
    },
    relatedCategory: "ev"
  },
  "ev-48v-40ah": {
    name: "48V 40Ah LFP",
    category: "ev",
    badge: "HC",
    brand: "TRONTEK",
    image: "battery-ev.jpeg",
    specs: "48V • 40Ah • 1920Wh • LFP • 1500+ Cycles • 15.2 kg",
    price: "Wholesale / On Enquiry",
    description: "High-capacity 48V option. 80-100 km extended range. 4-5 hour charge. Dual battery compatible. Smart BMS with app. 3+ year warranty.",
    details: {
      voltage: "48V",
      capacity: "40Ah",
      energy: "1920Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "1500+",
      weight: "15.2 kg",
      range: "80-100 km per charge",
      chargeTime: "4-5 hours",
      warranty: "3+ years",
      maintenance: "Smart BMS monitoring",
      ipRating: "IP65"
    },
    relatedCategory: "ev"
  },
  "ev-60v-40ah": {
    name: "60V 40Ah LFP",
    category: "ev",
    badge: "Range+",
    brand: "OKAYA EV",
    image: "battery-ev.jpeg",
    specs: "60V • 40Ah • 2400Wh • LFP • 1500+ Cycles • 18 kg",
    price: "Wholesale / On Enquiry",
    description: "Premium 60V performance. Guaranteed 100+ km range. 5-6 hour charge. Dual charging available. IP65+ rating. Bluetooth BMS. 4+ year lifespan.",
    details: {
      voltage: "60V",
      capacity: "40Ah",
      energy: "2400Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "1500+",
      weight: "18 kg",
      range: "100+ km per charge",
      chargeTime: "5-6 hours",
      warranty: "4+ years",
      maintenance: "Bluetooth BMS monitoring",
      ipRating: "IP65"
    },
    relatedCategory: "ev"
  },
  "ev-60v-50ah": {
    name: "60V 50Ah LFP",
    category: "ev",
    badge: "UHC",
    brand: "EXIDE LIVO",
    image: "battery-ev.jpeg",
    specs: "60V • 50Ah • 3000Wh • LFP • 1500+ Cycles • 22 kg",
    price: "Wholesale / On Enquiry",
    description: "Ultra-high capacity. 120-140 km single charge. 6-7 hour charge time. Heavy-duty scooters. Enterprise app monitoring. Warranty upgrade available.",
    details: {
      voltage: "60V",
      capacity: "50Ah",
      energy: "3000Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "1500+",
      weight: "22 kg",
      range: "120-140 km per charge",
      chargeTime: "6-7 hours",
      warranty: "4+ years",
      maintenance: "App-based monitoring",
      ipRating: "IP65"
    },
    relatedCategory: "ev"
  },
  "ev-72v-40ah": {
    name: "72V 40Ah NMC/LFP",
    category: "ev",
    badge: "Performance",
    brand: "TRONTEK",
    image: "battery-ev.jpeg",
    specs: "72V • 40Ah • 2880Wh • 1000-1500 Cycles • 20 kg",
    price: "Wholesale / On Enquiry",
    description: "Performance e-bikes & scooters. 150+ km extended range. 3C peak discharge. CAN communication ready. Dual battery stackable. Military-grade BMS. App monitoring included.",
    details: {
      voltage: "72V",
      capacity: "40Ah",
      energy: "2880Wh",
      chemistry: "NMC/LFP",
      cycles: "1000-1500",
      weight: "20 kg",
      range: "150+ km per charge",
      chargeTime: "3 hours",
      warranty: "4+ years",
      maintenance: "Military-grade BMS",
      ipRating: "IP67"
    },
    relatedCategory: "ev"
  },
  "inverter-12v-100ah-lith": {
    name: "12.8V 100Ah LiFePO4",
    category: "inverter",
    badge: "LFP 12V",
    brand: "EXIDE LIVO",
    image: "battery-ups.jpeg",
    specs: "12.8V • 100Ah • 1280Wh • LFP • 3000+ Cycles • 12 kg",
    price: "Wholesale / On Enquiry",
    description: "Zero-maintenance lithium for home inverters. 3000+ cycles = 8-10 years. Inverter compatible (Luminous, Microtek, Exide, Okaya). 3-5 hour charge. 70% lighter. Bluetooth BMS. 80% usable capacity.",
    details: {
      voltage: "12.8V",
      capacity: "100Ah",
      energy: "1280Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "3000+",
      weight: "12 kg",
      range: "3-5 hours home backup",
      chargeTime: "3-5 hours",
      warranty: "8-10 years design life",
      maintenance: "Zero maintenance",
      ipRating: "IP54"
    },
    relatedCategory: "inverter"
  },
  "inverter-12v-200ah-lith": {
    name: "12.8V 200Ah LiFePO4",
    category: "inverter",
    badge: "LFP 12V+",
    brand: "LIVGUARD",
    image: "battery-ups.jpeg",
    specs: "12.8V • 200Ah • 2560Wh • LFP • 3000+ Cycles • 23 kg",
    price: "Wholesale / On Enquiry",
    description: "Extended backup lithium. Dual battery stackable. 8-10 year lifespan. App monitoring included. Inverter universal fit. Fast 2-3 hour charge.",
    details: {
      voltage: "12.8V",
      capacity: "200Ah",
      energy: "2560Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "3000+",
      weight: "23 kg",
      range: "6-8 hours home backup",
      chargeTime: "2-3 hours",
      warranty: "8-10 years",
      maintenance: "Zero maintenance",
      ipRating: "IP54"
    },
    relatedCategory: "inverter"
  },
  "inverter-12v-300ah-lith": {
    name: "12.8V 300Ah LiFePO4",
    category: "inverter",
    badge: "LFP 12V++",
    brand: "OKAYA",
    image: "battery-ups.jpeg",
    specs: "12.8V • 300Ah • 3840Wh • LFP • 3000+ Cycles • 35 kg",
    price: "Wholesale / On Enquiry",
    description: "Premium triple-capacity lithium. Multi-unit stacking for mega backup. 10+ year design life. Enterprise BMS. Warranty upgrade to 7 years.",
    details: {
      voltage: "12.8V",
      capacity: "300Ah",
      energy: "3840Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "3000+",
      weight: "35 kg",
      range: "12-15 hours home backup",
      chargeTime: "4-5 hours",
      warranty: "10+ years",
      maintenance: "Enterprise BMS",
      ipRating: "IP54"
    },
    relatedCategory: "inverter"
  },
  "inverter-24v-100ah-lith": {
    name: "25.6V 100Ah LiFePO4",
    category: "inverter",
    badge: "LFP 24V",
    brand: "TRONTEK",
    image: "battery-ups.jpeg",
    specs: "25.6V • 100Ah • 2560Wh • LFP • 3000+ Cycles • 22 kg",
    price: "Wholesale / On Enquiry",
    description: "24V commercial UPS inverter solution. Higher voltage efficiency. Dual module stackable. Smart BMS with RS485 support. Industrial-grade reliability.",
    details: {
      voltage: "25.6V",
      capacity: "100Ah",
      energy: "2560Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "3000+",
      weight: "22 kg",
      range: "5-7 hours commercial backup",
      chargeTime: "3-4 hours",
      warranty: "10+ years",
      maintenance: "Smart BMS with RS485",
      ipRating: "IP54"
    },
    relatedCategory: "inverter"
  },
  "inverter-24v-200ah-lith": {
    name: "25.6V 200Ah LiFePO4",
    category: "inverter",
    badge: "LFP 24V+",
    brand: "EXIDE LIVO",
    image: "battery-ups.jpeg",
    specs: "25.6V • 200Ah • 5120Wh • LFP • 3000+ Cycles • 43 kg",
    price: "Wholesale / On Enquiry",
    description: "High-power 24V commercial system. Server room & telecom UPS compatible. Modular for large installations. CAN bus communication. Enterprise warranty options.",
    details: {
      voltage: "25.6V",
      capacity: "200Ah",
      energy: "5120Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "3000+",
      weight: "43 kg",
      range: "10-12 hours commercial",
      chargeTime: "4-5 hours",
      warranty: "10+ years",
      maintenance: "CAN bus communication",
      ipRating: "IP54"
    },
    relatedCategory: "inverter"
  },
  "inverter-48v-100ah-lith": {
    name: "51.2V 100Ah LiFePO4",
    category: "inverter",
    badge: "LFP 48V",
    brand: "LIVGUARD",
    image: "battery-ups.jpeg",
    specs: "51.2V • 100Ah • 5120Wh • LFP • 3000+ Cycles • 42 kg",
    price: "Wholesale / On Enquiry",
    description: "48V hybrid solar inverter compatible. Scalable system. MPPT controller friendly. 80% DoD usable. 10+ year lifespan. IP54 outdoor capable.",
    details: {
      voltage: "51.2V",
      capacity: "100Ah",
      energy: "5120Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "3000+",
      weight: "42 kg",
      range: "10-15 hours home backup",
      chargeTime: "3-4 hours",
      warranty: "10+ years",
      maintenance: "MPPT solar friendly",
      ipRating: "IP65"
    },
    relatedCategory: "inverter"
  },
  "inverter-48v-200ah-lith": {
    name: "51.2V 200Ah LiFePO4",
    category: "inverter",
    badge: "LFP 48V+",
    brand: "OKAYA",
    image: "battery-ups.jpeg",
    specs: "51.2V • 200Ah • 10.24kWh • LFP • 3000+ Cycles • 82 kg",
    price: "Wholesale / On Enquiry",
    description: "Premium 48V energy storage. Large home/commercial backup. Stacking to 50kWh+. Grid-tie hybrid ready. Smart monitoring with Bluetooth. 10+ year warranty upgrade.",
    details: {
      voltage: "51.2V",
      capacity: "200Ah",
      energy: "10.24kWh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "3000+",
      weight: "82 kg",
      range: "20-30 hours home backup",
      chargeTime: "4-5 hours",
      warranty: "10+ years",
      maintenance: "Smart Bluetooth monitoring",
      ipRating: "IP65"
    },
    relatedCategory: "inverter"
  },
  "storage-5kwh": {
    name: "5kWh ESS Wall Mount",
    category: "storage",
    badge: "5kWh",
    brand: "OEM",
    image: "battery-industrial.jpeg",
    specs: "48V • 100Ah • 5kWh • LFP • 3000+ Cycles • 42 kg",
    price: "Wholesale / On Enquiry",
    description: "Entry-level home energy storage. Wall-mount compact design. 4-6 hour home backup (typical load). Solar + grid hybrid. App monitoring. Plug & Play installation. 10+ year warranty.",
    details: {
      voltage: "48V",
      capacity: "100Ah (5kWh)",
      energy: "5000Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "3000+",
      weight: "42 kg",
      range: "4-6 hours home backup",
      chargeTime: "3-4 hours",
      warranty: "10+ years",
      maintenance: "Zero maintenance",
      ipRating: "IP54"
    },
    relatedCategory: "storage"
  },
  "storage-10kwh": {
    name: "10kWh ESS (Dual Stack)",
    category: "storage",
    badge: "10kWh",
    brand: "LIVGUARD",
    image: "battery-industrial.jpeg",
    specs: "2× 5kWh • 48V • LFP • 3000+ Cycles • 84 kg total",
    price: "Wholesale / On Enquiry",
    description: "Mid-range Powerwall solution. 8-12 hour family home backup. Stackable modular design. Solar + battery + grid integration. Smart load management app. Scalable to 50kWh+. 10+ year lifespan.",
    details: {
      voltage: "48V (Dual)",
      capacity: "200Ah (10kWh)",
      energy: "10000Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "3000+",
      weight: "84 kg",
      range: "8-12 hours family backup",
      chargeTime: "4-5 hours",
      warranty: "10+ years",
      maintenance: "Smart load management",
      ipRating: "IP54"
    },
    relatedCategory: "storage"
  },
  "storage-15kwh": {
    name: "15kWh ESS (Triple Stack)",
    category: "storage",
    badge: "15kWh",
    brand: "OKAYA",
    image: "battery-industrial.jpeg",
    specs: "3× 5kWh • 48V • LFP • 3000+ Cycles • 126 kg total",
    price: "Wholesale / On Enquiry",
    description: "Premium large-home/small-commercial backup. 24-36 hour family load support. Triple modular stacking. Advanced load balancing. Remote monitoring with AI forecasting. 10+ year warranty standard.",
    details: {
      voltage: "48V (Triple)",
      capacity: "300Ah (15kWh)",
      energy: "15000Wh",
      chemistry: "LiFePO4 (LFP)",
      cycles: "3000+",
      weight: "126 kg",
      range: "24-36 hours family backup",
      chargeTime: "5-6 hours",
      warranty: "10+ years",
      maintenance: "AI forecasting monitoring",
      ipRating: "IP54"
    },
    relatedCategory: "storage"
  },
  "solar-3kw": {
    name: "3kW Hybrid Solar Inverter",
    category: "solar",
    badge: "3kW",
    brand: "OEM",
    image: "battery-industrial.jpeg",
    specs: "3000W • 48V • MPPT • Grid-Tie & Off-Grid • WiFi Monitor",
    price: "Wholesale / On Enquiry",
    description: "Single-phase hybrid solar inverter. MPPT solar charge controller built-in. Compatible with 48V LiFePO4 batteries. Grid-tie + battery backup mode. WiFi monitoring app included. Ideal for 3-5 kW rooftop solar systems. 10-year warranty.",
    details: {
      voltage: "48V input",
      capacity: "3000W output",
      energy: "Variable based on load",
      chemistry: "N/A (Inverter)",
      cycles: "N/A",
      weight: "15-20 kg",
      range: "Compatible with 5-50kWh ESS",
      chargeTime: "Depends on solar input",
      warranty: "10 years",
      maintenance: "Minimal (inverter maintenance)",
      ipRating: "IP65"
    },
    relatedCategory: "solar"
  },
  "solar-5kw": {
    name: "5kW Hybrid Solar Inverter",
    category: "solar",
    badge: "5kW",
    brand: "OEM",
    image: "battery-industrial.jpeg",
    specs: "5000W • 48V • MPPT • Grid-Tie & Off-Grid • CAN Bus",
    price: "Wholesale / On Enquiry",
    description: "Single/3-phase hybrid solar inverter option. Advanced MPPT dual-tracker. Seamless battery charge/discharge. Grid export capability. CAN bus communication for large systems. WiFi + Bluetooth monitoring. Ideal for 5-10 kW solar systems. 10-year warranty.",
    details: {
      voltage: "48V input",
      capacity: "5000W output",
      energy: "Variable based on load",
      chemistry: "N/A (Inverter)",
      cycles: "N/A",
      weight: "20-25 kg",
      range: "Compatible with 10-100kWh ESS",
      chargeTime: "Depends on solar input",
      warranty: "10 years",
      maintenance: "Minimal (inverter maintenance)",
      ipRating: "IP65"
    },
    relatedCategory: "solar"
  },
  "industrial-vrla-12v-100-150ah": {
    name: "VRLA AGM 12V 100-150Ah",
    category: "industrial",
    badge: "AGM",
    brand: "LUMINOUS",
    image: "battery-industrial.jpeg",
    specs: "12V • 100-150Ah • 1200-1800Wh • VRLA • 300-500 Cycles",
    price: "Wholesale / On Enquiry",
    description: "Sealed lead-acid AGM batteries for telecom, UPS, and backup power. Zero maintenance. Valve-regulated. 10+ year design life. IP54 rated. Industry certifications included.",
    details: {
      voltage: "12V",
      capacity: "100-150Ah",
      energy: "1200-1800Wh",
      chemistry: "VRLA (AGM)",
      cycles: "300-500",
      weight: "30-35 kg",
      range: "Enterprise backup power",
      chargeTime: "8-10 hours",
      warranty: "5-10 years",
      maintenance: "Zero maintenance (sealed)",
      ipRating: "IP54"
    },
    relatedCategory: "industrial"
  },
  "industrial-vrla-24v-200-250ah": {
    name: "VRLA AGM 24V 200-250Ah",
    category: "industrial",
    badge: "Dual AGM",
    brand: "EXIDE",
    image: "battery-industrial.jpeg",
    specs: "24V • 200-250Ah • 4800-6000Wh • VRLA • 300-500 Cycles",
    price: "Wholesale / On Enquiry",
    description: "Twin 12V VRLA AGM batteries for enterprise data centre, hospital & critical infrastructure backup. Extreme reliability. Sealed zero-maintenance. Modular expansion capable. 10+ year design life.",
    details: {
      voltage: "24V (Dual 12V)",
      capacity: "200-250Ah",
      energy: "4800-6000Wh",
      chemistry: "VRLA (AGM)",
      cycles: "300-500",
      weight: "60-70 kg",
      range: "Data centre & hospital backup",
      chargeTime: "10-12 hours",
      warranty: "5-10 years",
      maintenance: "Zero maintenance",
      ipRating: "IP54"
    },
    relatedCategory: "industrial"
  },
  "industrial-gel-12v-100ah": {
    name: "GEL 12V 100Ah Mission-Critical",
    category: "industrial",
    badge: "Gel",
    brand: "OKAYA",
    image: "battery-industrial.jpeg",
    specs: "12V • 100Ah • 1200Wh • GEL • 1000+ Cycles",
    price: "Wholesale / On Enquiry",
    description: "High-reliability GEL battery for mission-critical systems. Solar-compatible. Extreme vibration resistance. 12+ year design life. Aerospace-grade reliability. Sealed maintenance-free.",
    details: {
      voltage: "12V",
      capacity: "100Ah",
      energy: "1200Wh",
      chemistry: "GEL",
      cycles: "1000+",
      weight: "32 kg",
      range: "Mission-critical backup",
      chargeTime: "8-10 hours",
      warranty: "5-7 years",
      maintenance: "Zero maintenance",
      ipRating: "IP65"
    },
    relatedCategory: "industrial"
  },
  "industrial-dg-diesel-gen": {
    name: "Diesel Generator Start (12V 200Ah)",
    category: "industrial",
    badge: "DG",
    brand: "SF SONIC",
    image: "battery-industrial.jpeg",
    specs: "12V • 200Ah • 2400Wh • VRLA • 600+ Cycles",
    price: "Wholesale / On Enquiry",
    description: "Heavy-duty diesel generator starter battery. Extreme cold-cranking capability. Industrial-strength terminals. 15+ year design life. Factory-sealed zero-maintenance. Mission-critical reliability.",
    details: {
      voltage: "12V",
      capacity: "200Ah",
      energy: "2400Wh",
      chemistry: "VRLA",
      cycles: "600+",
      weight: "50 kg",
      range: "Heavy-duty DG operations",
      chargeTime: "12-14 hours",
      warranty: "5-7 years",
      maintenance: "Zero maintenance",
      ipRating: "IP54"
    },
    relatedCategory: "industrial"
  }
};
